using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Xml;
using System.IO;

public class LevelManager : MonoBehaviour {
	private string outPutText;
	private int nMissToShrink;
	private int name;

	// Use this for initialization
	void Start () {
		//System.IO.File.WriteAllText("C:/Users/Eivind/Documents/BubbleShooter3D/Assets/Scripts/levelDummy.txt", "First try");
		makeLevel();
	}
	
	// Update is called once per frame
	void Update () {
		
	}

	private void makeLevel(){
		Debug.Log ("making level");
		string filepath = "C:/Users/Eivind/Documents/BubbleShooter3D/Assets/Resources/leveldata.xml";
		XmlDocument xmlDoc = new XmlDocument();
		
		if(File.Exists (filepath))
		{
			xmlDoc.Load(filepath);

			XmlElement root = xmlDoc.DocumentElement;
			
			XmlElement level = xmlDoc.CreateElement("level"); 

			XmlElement name = xmlDoc.CreateElement("name");
			XmlElement shrinkInterval = xmlDoc.CreateElement("shrinkInterval"); 
			XmlElement nColors = xmlDoc.CreateElement("nColors");
			XmlElement backGroundTex = xmlDoc.CreateElement("backGroundTex");

			name.InnerText = "LevelAutoGenerated";
			shrinkInterval.InnerText = "4";
			nColors.InnerText = "4";
			backGroundTex.InnerText = "woods";

			level.AppendChild(name);
			level.AppendChild(shrinkInterval);
			level.AppendChild(nColors);
			level.AppendChild(backGroundTex);
			float dist = 0.75f;
			int nBalls = 0;

			for(int i = -4; i <5; i++){
			
				if(i!=0){
					float d = i*1.25f;
					//Straights
					makeBall(d, 0, 0, level,xmlDoc);
					makeBall(0, d, 0, level,xmlDoc);
					makeBall(0, 0, d, level,xmlDoc);

					//Diagonals
					d = i*0.75f;
					makeBall(d, d, d, level,xmlDoc);
					makeBall(d, -d, d, level,xmlDoc);
					makeBall(d, -d, -d, level,xmlDoc);
					makeBall(d, d, -d, level,xmlDoc);
				}

			}

			/*
			for(int i = -4; i <5; i+= 2){
				for(int j = -4; j <5; j+= 2){
					for(int k = -4;k <5; k+=+ 2){
						if(!(i==0 && j==0 && k==0)){
							nBalls ++;
							float x = i*dist;
							float y = j*dist;
							float z = k*dist;
							XmlElement ball = xmlDoc.CreateElement("ball");
							ball.SetAttribute("x",x.ToString()); 
							ball.SetAttribute("y",y.ToString()); 
							ball.SetAttribute("z",z.ToString());

							if(nBalls%11==0)	ball.SetAttribute("type","stone");
							else {
								ball.SetAttribute("type","randColor");
							} 

							level.AppendChild(ball);
						}
					}
				}
			}*/

			root.AppendChild(level);			
			xmlDoc.Save(filepath); // save file.
		}
	}

	private void makeBall(float x, float y, float z, XmlElement level, XmlDocument xmlDoc){
		XmlElement ball = xmlDoc.CreateElement("ball");
		ball.SetAttribute("x",x.ToString()); 
		ball.SetAttribute("y",y.ToString()); 
		ball.SetAttribute("z",z.ToString());

		ball.SetAttribute("type","randColor");
	
	
		level.AppendChild(ball);

	}
}
